SKY-3: Footer.html design2
Aymammet/sky pull request #16
Opened 2023-01-23 05:27 UTC by anurmamedov

uploaded footer

2023-01-23 05:30 UTC, anurmamedov commented
Updated, review it.

2023-01-24 00:58 UTC, Aymammet commented
in commits description try to write exactly what changes you made.
Example : "design of social media icons changed", "display style of footer columns changed so that they are not broken in small size screens.", "minor bugs fixed", "error in line 3 that was made in previous commit fixed, 'sm' is replaced with 'md' "

2023-01-24 00:58 UTC, Aymammet commented
Send image of your changes. It is hard to see what changes you made by just looking at code. Especially in design changes. Place different screen size images, to get enough information how they look like.

2023-01-24 01:39 UTC, anurmamedov commented
Now.
![Screenshot 2023-01-23 203653](https://user-images.githubusercontent.com/112652150/214195397-8da39186-9a3a-490f-a204-7b7a8b0055b8.png)

Before.
![before-Screenshot 2023-01-23 203851](https://user-images.githubusercontent.com/112652150/214195520-d15af1d1-69f4-49f8-b166-a8020e58ff4e.png)

2023-01-24 02:38 UTC, Aymammet requested changes

2023-01-24 02:53 UTC, Aymammet requested changes

2023-01-24 02:53 UTC, Aymammet commented on templates/footer.html
> +  <!-- Remove the container if you want to extend the Footer to full width.-->
Remove commented lines

2023-01-24 02:56 UTC, Aymammet requested changes

2023-01-24 02:56 UTC, Aymammet commented on templates/footer.html
> +</html>
```suggestion
```

2023-01-24 02:56 UTC, Aymammet commented on templates/footer.html
> +  <!-- Remove the container if you want to extend the Footer to full width.-->
```suggestion
```

2023-01-24 02:59 UTC, Aymammet approved these changes

2023-01-24 02:59 UTC, merged