Sky-6: Profile detail design
Aymammet/sky pull request #17
Opened 2023-01-26 03:25 UTC by anurmamedov

1. "edit" button dragged up on top
2. "save changes" button removed
3.  Username Added on top , first name and last name removed
4. Occupation, Bio, No# of posts , liked posts, disliked posts , joined date, last visited dated added.
5. Size of column re-adjusted for each div. 
6. Main div's column set on 11.
7. No clashes on on dimensions: Responsive.
----------------------------------*-----------------------*-------------------
![Screenshot 2023-01-25 222129](https://user-images.githubusercontent.com/112652150/214752335-229e3f6e-1e63-42f8-a9ad-3a77a7525eb9.png)
![Screenshot 2023-01-25 222208](https://user-images.githubusercontent.com/112652150/214752336-531b8f91-a9e4-4f02-87a6-0dfc4ff5b62e.png)
![Screenshot 2023-01-25 222229](https://user-images.githubusercontent.com/112652150/214752337-b28ea7a9-5c75-43dd-ad61-c4b61243f07c.png)
![Screenshot 2023-01-25 222249](https://user-images.githubusercontent.com/112652150/214752338-10fe6c92-d140-4007-82d8-01fb4e32cf13.png)
![Screenshot 2023-01-25 222303](https://user-images.githubusercontent.com/112652150/214752339-5a2d13d9-9a4f-4be5-a545-765968dd6c5c.png)
![Screenshot 2023-01-25 222331](https://user-images.githubusercontent.com/112652150/214752341-8a70cf4e-0206-4d3b-869d-d59b24f6a401.png)
![Screenshot 2023-01-25 222439](https://user-images.githubusercontent.com/112652150/214752342-8050bc5a-3a5d-4b0e-81e9-b98ec4e55ecd.png)

2023-01-26 03:48 UTC, Aymammet requested changes

2023-01-26 03:48 UTC, Aymammet commented on templates/profile-details.html
> +</head>
Why we need these lines? They are already exists in base.html?

2023-01-26 03:48 UTC, Aymammet commented on templates/profile-details.html
> +    <div style="background-color: whitesmoke;" class="container">
use style.css for custom styles

2023-01-26 03:48 UTC, Aymammet commented on templates/profile-details.html
> +                    <li class="breadcrumb-item"><a href="javascript:void(0)">Profile</a></li>
what is javascript : void(0) here?

2023-01-26 03:48 UTC, Aymammet commented on templates/profile-details.html
> +                                    <h6 class="mb-4 fs-6" style="color:grey">Username</h6>
Why we need this Username expression here? it is alreade known as username with "@" sign

2023-01-26 03:48 UTC, Aymammet commented on templates/profile-details.html
> +                    POSTS
Where are posts? This page should be ready with all its components.

2023-01-26 03:48 UTC, Aymammet commented on templates/profile-details.html
> +</html>
```suggestion
</html>

```

2023-01-26 03:49 UTC, Aymammet commented
Why we have green, gray, orange background colors?

2023-01-26 03:52 UTC, Aymammet commented
Why the color of edit button is different from others?

2023-01-26 03:52 UTC, Aymammet commented
Sizes of buttons can be same

2023-01-28 05:02 UTC, Aymammet requested changes

2023-01-28 05:02 UTC, Aymammet commented on templates/profile-details.html
> +                <!-- START OF LEFT PART OF COLUMN -->
you mena left sidebar?

2023-01-28 05:02 UTC, Aymammet commented
Can you send the last images of your changes? large/medium/mobile

2023-01-29 23:47 UTC, anurmamedov commented
[profile details updated3] pushed to github.
* Comments modified.
* Pictures attached (small, medium, large)

![large size_post detail](https://user-images.githubusercontent.com/112652150/215362888-76970d98-13ac-4ca6-9c55-e5ed2bfb30dc.png)
![medium size_post detail](https://user-images.githubusercontent.com/112652150/215362893-39d05019-4b4f-4d1e-aeb7-e077eb3676d3.png)
![small size_post detail](https://user-images.githubusercontent.com/112652150/215362896-251d271e-f6c3-490e-8c7f-644873a70f97.png)

2023-01-30 00:09 UTC, Aymammet commented
For posts that we display in right side of profile details :

2023-01-30 00:15 UTC, Aymammet commented
7. Under the username there are 3 buttons. Their size should be identical for better user experience.
8. What about to use fontawesome icons for some buttons. (as example instead of writing edit we can place fontawesome pen icon)

2023-01-30 22:07 UTC, Aymammet requested changes
it is ok for code and design for now. But why we have two same files in template folder. (**profile-detail.html** **and profile-details.html**) ?

2023-01-31 02:21 UTC, anurmamedov commented
i made a mistake, renamed it now. back to profile-details.

2023-01-31 03:29 UTC, Aymammet approved these changes

2023-01-31 03:29 UTC, merged