Sky-9: Login.html design
Aymammet/sky pull request #18
Opened 2023-01-30 01:23 UTC by anurmamedov

* login details upload and readme text updated

![large size login detail](https://user-images.githubusercontent.com/112652150/215368808-acc7b0ac-307a-44d0-b2d4-610a2cb420cb.png)
![medium size login detail](https://user-images.githubusercontent.com/112652150/215368816-3a8f0919-302a-4518-98ae-1ecc5e5ae697.png)
![between small medium size_login details](https://user-images.githubusercontent.com/112652150/215368822-16f8b844-4a9e-4698-a34e-c0d3d23ff35c.png)
![small size login detail](https://user-images.githubusercontent.com/112652150/215368826-6ff1d338-488a-46c4-9a15-286ac56605e3.png)

2023-01-30 04:17 UTC, Aymammet requested changes
1. Show error messages how they look like under each input. (maybe red color)
a. your password is wrong
b. this username does not exists

2. label should be on top of the input

2023-01-30 04:30 UTC, Aymammet requested changes

2023-01-30 04:30 UTC, Aymammet commented on README.md
> +# SKY: Social Media Application, named Sky
remove

2023-01-30 04:30 UTC, Aymammet commented on templates/login.html
> +              <input type="password" id="form2Example2" class="form-control" />
placeholder and fontawesome icon

2023-01-30 22:09 UTC, Aymammet commented on templates/login.html
> +              <input type="password" id="form2Example2" class="form-control" />
is this done?

2023-01-31 02:16 UTC, anurmamedov commented on templates/login.html
> +              <input type="password" id="form2Example2" class="form-control" />
yes, it is

2023-01-31 03:31 UTC, Aymammet approved these changes

2023-01-31 03:32 UTC, merged