an/SKY-11: Profile-edit page design
Aymammet/sky pull request #23
Opened 2023-02-01 06:02 UTC by anurmamedov

1. Fontawesome icons added and profile page design created

2023-02-01 14:28 UTC, Aymammet requested changes

2023-02-01 14:28 UTC, Aymammet commented on templates/profile-edit.html
> +    <body>
can be removed

2023-02-01 14:28 UTC, Aymammet commented on templates/profile-edit.html
> +    </body>
can be removed

2023-02-03 03:33 UTC, anurmamedov commented on templates/profile-edit.html
> +    </body>
removed

2023-02-03 03:35 UTC, anurmamedov reviewed
Profile-edit page body removed

2023-02-03 03:55 UTC, Aymammet requested changes
Your task is about profile edit page design but there is profile create.html file. 
Shouldn't they be seperated?

2023-02-03 03:59 UTC, anurmamedov commented
it is post  edit. i called commit by mistake profile edit.  It is post edit

2023-02-03 04:32 UTC, Aymammet approved these changes

2023-02-03 04:32 UTC, merged